profile:
    path:     /
    defaults: { _controller: "DataSourceBundle:Profile:index" }

profile_show:
    path:     /{id}/show
    defaults: { _controller: "DataSourceBundle:Profile:show" }

profile_new:
    path:     /new
    defaults: { _controller: "DataSourceBundle:Profile:new" }

profile_create:
    path:     /create
    defaults: { _controller: "DataSourceBundle:Profile:create" }
    methods:  POST

profile_edit:
    path:     /{id}/edit
    defaults: { _controller: "DataSourceBundle:Profile:edit" }

profile_update:
    path:     /{id}/update
    defaults: { _controller: "DataSourceBundle:Profile:update" }
    methods:  [POST, PUT]

profile_delete:
    path:     /{id}/delete
    defaults: { _controller: "DataSourceBundle:Profile:delete" }
    methods:  [POST, DELETE]
