# src/DataSourceBundle/Resources/config/doctrine/Category.orm.yml
DataSourceBundle\Entity\Category:
  repositoryClass: DataSourceBundle\Repository\CategoryRepository
  type: entity
  table: category
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
      unique: true
    created_at:
      type: datetime
      nullable: true
    updated_at:
      type: datetime
      nullable: true
  lifecycleCallbacks:
    prePersist: [ setCreatedAtValue ]
    preUpdate: [ setUpdatedAtValue ]